[package]
name = "kauma_hot_reload"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8.20"
notify-debouncer-full = "0.5.0"
kauma_proc_macro = { path = "crates/kauma_proc_macro" }
kauma_shared_types = { path = "crates/kauma_shared_types" }
