[package]
name = "kauma_hot_reload"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[[bin]]
name = "kauma_rebuild"
path = "src/main.rs"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
toml = "0.8.20"
notify-debouncer-full = "0.5.0"
