[package]
name = "kauma_hot_reload"
version = "0.1.0"
edition = "2021"

[dependencies]
kauma_proc_macro = { path = "crates/kauma_proc_macro" }
kauma_common = { path = "crates/kauma_common" }
toml = "0.8.20"
notify-debouncer-full = "0.5.0"
libloading = "0.8.6"
